// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcClassroom.Data;

#nullable disable

namespace MvcClassroom.Migrations
{
    [DbContext(typeof(MvcClassroomContext))]
    [Migration("20230322131519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("MvcClassroom.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalStudent")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalStudentPercentage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Classroom");
                });
#pragma warning restore 612, 618
        }
    }
}
